stages:

  preprocess:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw/insurance.csv
    - src/data/make_dataset.py
    - config/params.yaml
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  train_linear:
    cmd: python src/models/train_linear.py
    deps:
    - config/params.yaml
    - data/processed/train.csv
    - data/processed/test.csv
    - src/models/train_linear.py
    outs:
    - models/linear.pkl
    metrics:
    - dvclive/linear/metrics.json
    plots:
    - dvclive/linear/plots

  train_decision_tree:
    cmd: python src/models/train_decision_tree.py
    deps:
    - config/params.yaml
    - data/processed/train.csv
    - data/processed/test.csv
    - src/models/train_decision_tree.py
    outs:
    - models/decision_tree.pkl
    - reports/figures/decision_tree_structure.png
    metrics:
    - dvclive/decision_tree/metrics.json
    plots:
    - dvclive/decision_tree/plots

  train_catboost:
    cmd: python src/models/train_catboost.py
    deps:
    - config/params.yaml
    - data/processed/train.csv
    - data/processed/test.csv
    - src/models/train_catboost.py
    outs:
    - models/catboost.cbm
    - reports/figures/catboost_feature_importance.png
    metrics:
    - dvclive/catboost/metrics.json
    plots:
    - dvclive/catboost/plots

  train_xgboost:
    cmd: python src/models/train_xgboost.py
    deps:
    - config/params.yaml
    - data/processed/train.csv
    - data/processed/test.csv
    - src/models/train_xgboost.py
    outs:
    - models/xgboost.json
    - reports/figures/xgboost_feature_importance.png
    metrics:
    - dvclive/xgboost/metrics.json
    plots:
    - dvclive/xgboost/plots
params:
- dvclive/linear/params.yaml
- dvclive/decision_tree/params.yaml
- dvclive/catboost/params.yaml
- dvclive/xgboost/params.yaml
metrics:
- dvclive/linear/metrics.json
- dvclive/decision_tree/metrics.json
- dvclive/catboost/metrics.json
- dvclive/xgboost/metrics.json
plots:
- dvclive/linear/plots/metrics:
    x: step
- dvclive/decision_tree/plots/metrics:
    x: step
- dvclive/catboost/plots/metrics:
    x: step
- dvclive/xgboost/plots/metrics:
    x: step
