stages:

  preprocess:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw/insurance.csv
    - src/data/make_dataset.py
    params:
    - config/params.yaml:
      - base
      - data
    outs:
    - data/processed/train.csv
    - data/processed/test.csv
    - data/processed/data_x.npy
    - data/processed/data_y.npy
    - data/processed/insurance_processed.csv

  train_linear:
    cmd: python src/models/train_linear.py
    deps:
    - data/processed/train.csv
    - data/processed/test.csv
    - src/models/train_linear.py
    params:
    - config/params.yaml:
      - base
      - models.linear
    outs:
    - models/linear.pkl
    # - dvclive/linear/params.yaml
    - reports/figures/linear_coefficients.png
    - reports/linear_coefficients.json
    metrics:
    - dvclive/linear/metrics.json
    plots:
    - dvclive/linear/plots

  train_decision_tree:
    cmd: python src/models/train_decision_tree.py
    deps:
    - data/processed/train.csv
    - data/processed/test.csv
    - src/models/train_decision_tree.py
    params:
    - config/params.yaml:
      - base
      - models.decision_tree
    outs:
    - models/decision_tree.pkl
    # - dvclive/decision_tree/params.yaml
    - reports/figures/decision_tree_structure.png
    metrics:
    - dvclive/decision_tree/metrics.json
    plots:
    - dvclive/decision_tree/plots

  train_catboost:
    cmd: python src/models/train_catboost.py
    deps:
    - data/processed/train.csv
    - data/processed/test.csv
    - src/models/train_catboost.py
    params:
    - config/params.yaml:
      - base
      - models.catboost
    outs:
    - models/catboost.cbm
    # - dvclive/catboost/params.yaml
    - reports/figures/catboost_feature_importance.png
    metrics:
    - dvclive/catboost/metrics.json
    plots:
    - dvclive/catboost/plots

  train_xgboost:
    cmd: python src/models/train_xgboost.py
    deps:
    - data/processed/train.csv
    - data/processed/test.csv
    - src/models/train_xgboost.py
    params:
    - config/params.yaml:
      - base
      - models.xgboost
    outs:
    - models/xgboost.json
    # - dvclive/xgboost/params.yaml
    - reports/figures/xgboost_feature_importance.png
    metrics:
    - dvclive/xgboost/metrics.json
    plots:
    - dvclive/xgboost/plots

  train_ann:
    cmd: python src/models/train_ann.py
    deps:
    - data/processed/train.csv
    - data/processed/test.csv
    - src/models/train_ann.py
    params:
    - config/params.yaml:
      - base
      - models.ann
    outs:
    - models/ann.keras
    # - dvclive/ann/params.yaml
    - reports/figures/ann_loss_curve.png
    - reports/figures/ann_model_graph.png
    - reports/figures/ann_weights_layer_1.png
    - reports/figures/ann_weights_layer_2.png
    - reports/figures/ann_weights_layer_3.png
    metrics:
    - dvclive/ann/metrics.json
    plots:
    - dvclive/ann/plots

# Глобальные параметры, метрики и графики
params:
- config/params.yaml
metrics:
- dvclive/linear/metrics.json
- dvclive/decision_tree/metrics.json
- dvclive/catboost/metrics.json
- dvclive/xgboost/metrics.json
- dvclive/ann/metrics.json
plots:
- dvclive/linear/plots/metrics:
    x: step
- dvclive/decision_tree/plots/metrics:
    x: step
- dvclive/catboost/plots/metrics:
    x: step
- dvclive/xgboost/plots/metrics:
    x: step
- dvclive/ann/plots/metrics:
    x: step
